### PR TITLE
Make zsh keybindings work for all modes

### LINKED ISSUE #34: Keybindings not working for vi command mode
After sourcing the plugin, the `^G^*` keybindings work for `emacs` and `viins` modes. However the widgets aren't bound to anything in `vicmd` mode.

Fundamentally, this is because the zsh version of `__fzf_git_init` doesn't explicitly specify a mode for `bindkey`, which for vi mode users means all keybindings default to `viins`.

To fix this, minimally `-M vicmd` must be specified in its own call to `bindkey`.

~~Possibly related to #23.~~ Nvm, I don't think so.

### PR DESCRIPTION
**Pull request by cohml**
This PR ensures that when sourced, the plugin binds all `^G^*` actions irrespective of editing mode.

Thus all keybindings will be available for emacs users as well as vi mode users in both insert and command mode.

Resolves #34

### CODE REVIEW

File: fzf-git.sh [hunk 1]
```diff
@@ -256,8 +256,10 @@ elif [[ -n "${ZSH_VERSION:-}" ]]; then
     for o in "$@"; do
       eval "fzf-git-$o-widget() { local result=\$(_fzf_git_$o | __fzf_git_join); zle reset-prompt; LBUFFER+=\$result }"
       eval "zle -N fzf-git-$o-widget"
-      eval "bindkey '^g^${o[1]}' fzf-git-$o-widget"
-      eval "bindkey '^g${o[1]}' fzf-git-$o-widget"
+      for m in emacs vicmd viins; do
```
Comment (junegunn) [inline fzf-git.sh:259]:
```
__fzf_git_init:5: scalar parameter m created globally in function __fzf_git_init
```

Comment (jesperronn) [reply fzf-git.sh:259]: Regarding

> But why bind e.g., both ^Gf and ^G^F? 

I can explain that from a usability perspective. Depending on where you place your fingers and how fast you type, then both keystrokes are useful.

Of course, only one of them will respond and activate the action.

However, when typing fast, you can decide to use one hand to place a finger and press the CTRL 

At some point your finger will release CTRL.

Another finger or two can then press `G` followed by the action, for example `B`

You either release the CTRL finger before OR after pressing the action. This is why it is really smart to register both keyboard shortcuts 👍

Comment (junegunn) [reply fzf-git.sh:259]: Thanks @jesperronn for the comment. Yes, that makes a lot of sense.

The real reason we decided to have two sets of bindings is described in https://github.com/junegunn/fzf-git.sh?tab=readme-ov-file#usage

**Comment by junegunn** [comment]
Thanks for your patience. This just slipped my mind.
