### PR TITLE
Redirect the terminal to stdin of editor to work-around vim bug (#99)

### LINKED ISSUE #99: Using vim (ALT-E) destroys terminal state
I'm using Git Bash inside Windows Terminal.
If I there use the ALT-E action, for example from the files action, without an EDITOR set or set to `vim`, it behaves strange.

- first for a second "Vim: Warning: Input is not from a terminal" is displayed, then vim comes up but as far as I can tell behaves normal
- behaves normal except for being in replace mode immediately which imho is one of the most useless features of vim
- after leaving vim and leaving fzf now the terminal is in a wonky state

If I for example now do "CTRL+O ?", it looks like

```plain
CTRL-G ? to show this list
                          CTRL-G CTRL-F for Files
                                                 CTRL-G CTRL-B for Branches
                                                                           CTRL-G CTRL-T for Tags
                                                                                                 CTRL-G CTRL-R for Remotes
                                                                                                                          CTRL-G CTRL-H for commit Hashes
                                                                                                                                                         CTRL-G CTRL-S for Stashes
                                                                                                                                                                                  CTRL-G CTRL-L for reflogs
                                                                                                                                                                                                           CTRL-G CTRL-W for Worktrees
                                                                                                                                                                                                                                      CTRL-G CTRL-E for Each ref (git for-each-ref)
```
until I `reset` the state.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #99

### CODE REVIEW

File: fzf-git.sh [hunk 1]
```diff
@@ -298,7 +298,7 @@ _fzf_git_each_ref() {
     --no-hscroll \
     --bind 'ctrl-/:change-preview-window(down,70%|hidden|)' \
     --bind "ctrl-o:execute-silent:bash \"$__fzf_git\" --list {1} {2}" \
-    --bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) > /dev/tty" \
+    --bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) </dev/tty >/dev/tty" \
```
Comment (junegunn) [inline fzf-git.sh]:
```suggestion
    --bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) < /dev/tty > /dev/tty" \
```
